module.exports = [
  {
    id: 1,
    nome: 'Oversized Shadow Tee',
    preco: 119.00,
    descricao: 'Camiseta oversized preta da coleção Urban Pulse.',
    tipo: 'camiseta',
    categoria: 'parte_superior',
    cor: 'preto',
    estilo: 'streetwear',
    colecao: 'Urban Pulse',
    imagem: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 2,
    nome: 'Urban Grey Hoodie',
    preco: 229.00,
    descricao: 'Moletom streetwear cinza da coleção Urban Pulse.',
    tipo: 'moletom',
    categoria: 'parte_superior',
    cor: 'cinza',
    estilo: 'streetwear',
    colecao: 'Urban Pulse',
    imagem: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 3,
    nome: 'Night Flow Jacket',
    preco: 289.00,
    descricao: 'Jaqueta street preta da coleção Urban Pulse.',
    tipo: 'jaqueta',
    categoria: 'parte_superior',
    cor: 'preto',
    estilo: 'streetwear',
    colecao: 'Urban Pulse',
    imagem: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 4,
    nome: 'Street Signal Tee',
    preco: 109.00,
    descricao: 'Camiseta street branca da coleção Urban Pulse.',
    tipo: 'camiseta',
    categoria: 'parte_superior',
    cor: 'branco',
    estilo: 'streetwear',
    colecao: 'Urban Pulse',
    imagem: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 5,
    nome: 'Baggy Void Pants',
    preco: 199.00,
    descricao: 'Calça baggy preta da coleção Urban Pulse.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'preto',
    estilo: 'streetwear',
    colecao: 'Urban Pulse',
    imagem: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 6,
    nome: 'Cargo Motion Grey',
    preco: 219.00,
    descricao: 'Calça cargo cinza da coleção Urban Pulse.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'cinza',
    estilo: 'streetwear',
    colecao: 'Urban Pulse',
    imagem: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 7,
    nome: 'Denim Baggy Core',
    preco: 209.00,
    descricao: 'Calça jeans baggy azul da coleção Urban Pulse.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'azul',
    estilo: 'streetwear',
    colecao: 'Urban Pulse',
    imagem: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 8,
    nome: 'Sand Drift Pants',
    preco: 189.00,
    descricao: 'Calça streetwear bege da coleção Urban Pulse.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'bege',
    estilo: 'streetwear',
    colecao: 'Urban Pulse',
    imagem: 'https://images.unsplash.com/photo-1506629905607-d405b7a10db9?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 9,
    nome: 'Neon Code Tee',
    preco: 129.00,
    descricao: 'Blusa streetwear roxa da coleção Neon District.',
    tipo: 'camiseta',
    categoria: 'parte_superior',
    cor: 'roxo',
    estilo: 'streetwear',
    colecao: 'Neon District',
    imagem: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 10,
    nome: 'Purple Rush Hoodie',
    preco: 239.00,
    descricao: 'Moletom com detalhe neon da coleção Neon District.',
    tipo: 'moletom',
    categoria: 'parte_superior',
    cor: 'roxo',
    estilo: 'streetwear',
    colecao: 'Neon District',
    imagem: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 11,
    nome: 'District Wave Jacket',
    preco: 319.00,
    descricao: 'Jaqueta street neon da coleção Neon District.',
    tipo: 'jaqueta',
    categoria: 'parte_superior',
    cor: 'preto',
    estilo: 'streetwear',
    colecao: 'Neon District',
    imagem: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 12,
    nome: 'Flash Line Tee',
    preco: 115.00,
    descricao: 'Camiseta branca com estilo street da coleção Neon District.',
    tipo: 'camiseta',
    categoria: 'parte_superior',
    cor: 'branco',
    estilo: 'streetwear',
    colecao: 'Neon District',
    imagem: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 13,
    nome: 'Signal Baggy Pants',
    preco: 209.00,
    descricao: 'Calça baggy preta neon da coleção Neon District.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'preto',
    estilo: 'streetwear',
    colecao: 'Neon District',
    imagem: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 14,
    nome: 'Future Cargo Black',
    preco: 229.00,
    descricao: 'Calça cargo oversized da coleção Neon District.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'preto',
    estilo: 'streetwear',
    colecao: 'Neon District',
    imagem: 'https://images.unsplash.com/photo-1506629905607-d405b7a10db9?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 15,
    nome: 'Edge Flow Baggy',
    preco: 215.00,
    descricao: 'Calça larga streetwear da coleção Neon District.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'preto',
    estilo: 'streetwear',
    colecao: 'Neon District',
    imagem: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 16,
    nome: 'Steel Motion Pants',
    preco: 205.00,
    descricao: 'Calça cinza larga da coleção Neon District.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'cinza',
    estilo: 'streetwear',
    colecao: 'Neon District',
    imagem: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 17,
    nome: 'Raw Sand Tee',
    preco: 99.00,
    descricao: 'Camiseta bege minimalista da coleção Raw Minimal.',
    tipo: 'camiseta',
    categoria: 'parte_superior',
    cor: 'bege',
    estilo: 'streetwear',
    colecao: 'Raw Minimal',
    imagem: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 18,
    nome: 'Core Minimal Hoodie',
    preco: 219.00,
    descricao: 'Moletom minimalista da coleção Raw Minimal.',
    tipo: 'moletom',
    categoria: 'parte_superior',
    cor: 'bege',
    estilo: 'streetwear',
    colecao: 'Raw Minimal',
    imagem: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 19,
    nome: 'Earth Tone Jacket',
    preco: 279.00,
    descricao: 'Jaqueta bege streetwear da coleção Raw Minimal.',
    tipo: 'jaqueta',
    categoria: 'parte_superior',
    cor: 'bege',
    estilo: 'streetwear',
    colecao: 'Raw Minimal',
    imagem: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 20,
    nome: 'Clean Oversized Tee',
    preco: 109.00,
    descricao: 'Camiseta oversized branca da coleção Raw Minimal.',
    tipo: 'camiseta',
    categoria: 'parte_superior',
    cor: 'branco',
    estilo: 'streetwear',
    colecao: 'Raw Minimal',
    imagem: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 21,
    nome: 'Beige Drift Baggy',
    preco: 189.00,
    descricao: 'Calça baggy bege da coleção Raw Minimal.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'bege',
    estilo: 'streetwear',
    colecao: 'Raw Minimal',
    imagem: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 22,
    nome: 'Raw Cargo Sand',
    preco: 205.00,
    descricao: 'Calça cargo areia da coleção Raw Minimal.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'bege',
    estilo: 'streetwear',
    colecao: 'Raw Minimal',
    imagem: 'https://images.unsplash.com/photo-1506629905607-d405b7a10db9?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 23,
    nome: 'Loose Fade Denim',
    preco: 215.00,
    descricao: 'Calça jeans larga clara da coleção Raw Minimal.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'azul claro',
    estilo: 'streetwear',
    colecao: 'Raw Minimal',
    imagem: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  },
  {
    id: 24,
    nome: 'Concrete Wide Pants',
    preco: 199.00,
    descricao: 'Calça minimalista cinza da coleção Raw Minimal.',
    tipo: 'calca',
    categoria: 'parte_inferior',
    cor: 'cinza',
    estilo: 'streetwear',
    colecao: 'Raw Minimal',
    imagem: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    imagem_sem_fundo: null,
    estoque: 15
  }
];
